from AppMenus.Accounts_menu.AccountsMenu import AccountsMenu
from AppMenus.Accounts_menu.AccountsMenu_main import AccountsMenu_main
from AppMenus.Accounts_menu.AccountsMenu_debts import AccountsMenu_debts
from AppMenus.Accounts_menu.AccountsMenu_stat import AccountsMenu_stat

from AppMenus.Categories_menu.CategoriesMenu import CategoriesMenu
from AppMenus.Categories_menu.Categories_buttons_menu import Categories_buttons_menu
from AppMenus.Categories_menu.Incomes_buttons_menu import Incomes_buttons_menu

from AppMenus.Transaction_menu.TransactionMenu import Transaction_menu
from AppMenus.Transaction_menu.Transaction_menu_in import Transaction_menu_in
from AppMenus.Transaction_menu.date_label_for_transaction_history_menu import date_label_for_transaction_history_menu

from AppMenus.Budget_menu.BudgetMenu import BudgetMenu
from AppMenus.Budget_menu.BudgetMenu_in import BudgetMenu_in

from AppMenus.CashMenus.MenuForAnewTransaction import menu_for_a_new_transaction
